# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin Koffroth
email: ktkoffroth@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, My name is Kevin Koffroth, I'm an aspiring Computer Engineer 
  currently working on my undergraduate degree at the University of
  Georgia, and this is my personal website! I use it as the hub of my 
  internet presence, and it mainly serves to host my project 
  portfolio and blog posts about anything that interests me. I created 
  this site not only as a hub, but alsoas a means to practice my 
  technical and creative writing skills. I hope you enjoy your stay
  here, and feel free to email me with any questions, concerns, or 
  otherwise interesting things! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: N/A
github_username:  ktkoffroth

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
